version: "3.5"
services:
  ubuntu:
    build: .
    image: ubuntu:0.1.9
    container_name: ubuntu
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
    # entrypoint: /bin/bash
    ports:
      - "233:22"
    networks:
      dockernet:
        ipv4_address: 10.10.50.111

networks:
  dockernet:
    external: true
  eth0:
    driver: bridge
    ipam:
      config:
        - subnet: 11.5.0.0/8
