version: "3.5"
services:
  ubuntu:
    build: .
    image: ubuntu:0.1.7
    container_name: ubuntu
    stdin_open: true
    tty: true
    # entrypoint: /bin/bash
    ports:
      - "233:22"
    networks:
      eth0:
        ipv4_address: 10.5.0.1
networks:
  dockernet:
    external: true
  eth0:
    driver: bridge
    ipam:
      config: 
        - subnet: 10.5.0.0/8
     
       
